### ISSUE TITLE
"Why don't I have files with names starting with Fiddler, and after comparing with the video, I noticed that some files are missing?"

### ISSUE THREAD

**Issue by dmarkdmark** [auto-yui-patch/fiddler-everywhere-patch-automated#16]
**Is your feature request related to a problem? Please describe.**

![recording](https://github.com/user-attachments/assets/f2f4fd17-56da-43ec-941b-3aac63f4045d)

**Describe the solution you'd like**

"I want this installer, and then once I launch it, I can use Fiddler Everywhere."
"Latest version 6.0"
![Clip_2024-12-24_16-59-57](https://github.com/user-attachments/assets/4d975ec1-3d7c-4e66-9391-5f307eec9b62)

**Describe alternatives you've considered**
nothing

**Additional context**
nothing

**Comment by sipsuru** [comment]
You need to follow the instructions.

I don't provide pre-patched installers here.
So you need to `fork the repository` -> `enable actions for forked repository` -> `run a workflow action`

So the patched application `Fiddler-Everywhere-V6.0.0-Patched` artifact will be in **your forked repository**.

Again you need to follow instructions.

**Comment by sipsuru** [comment]
And if Chinese Instructions (Translated) misleaded you. You're warmly welcomed to improve Chinese README
